<hr/>
<div class="row">
  <div class="col-sm-4">
    <p><strong><?=$this->transEsc('Search Options')?></strong></p>
    <ul>
      <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
      <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
    </ul>
  </div>
  <div class="col-sm-4">
    <p><strong><?=$this->transEsc('Find More')?></strong></p>
    <ul>
      <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
      <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
      <li><a href="<?=$this->url('search-reserves')?>"><?=$this->transEsc('Course Reserves')?></a></li>
      <li><a href="http://libraryguides.mtsu.edu/newbooks"><?=$this->transEsc('New Items')?></a></li>
    </ul>
  </div>
  <div class="col-sm-4">
    <p><strong><?=$this->transEsc('Need Help?')?></strong></p>
    <ul>
      <li><a href="<?=$this->url('help-home')?>?topic=search" class="help-link" title="<?=$this->transEsc('Search Tips')?>"><?=$this->transEsc('Search Tips')?></a></li>
      <li><a href="http://libanswers.mtsu.edu/form.php?queue_id=756"><?=$this->transEsc('Ask A Librarian')?></a></li>
      <li><a href="http://libanswers.mtsu.edu"><?=$this->transEsc('FAQs')?></a></li>
    </ul>
  </div>
  <div class="col-sm-4">
    <p><strong><?=$this->transEsc('Limit to:')?></strong></p>
    <ul>
      <li><a href="https://find.mtsu.edu/vufind/Search/Results?type=AllFields&filter%5B%5D=collection%3A%22Curriculum+Collection%22"><?=$this->transEsc('Curriculum Collection')?></a></li>
      <li><a href="https://find.mtsu.edu/vufind/Search/Results?type=AllFields&filter%5B%5D=collection%3A%22Center+for+Popular+Music%22"><?=$this->transEsc('Center for Popular Music')?></a></li>
      <li><a href="https://find.mtsu.edu/vufind/Search/Results?type=AllFields&filter%5B%5D=collection%3A%22Media+Collection%22"><?=$this->transEsc('Media Collection')?></a></li>
      <li><a href="https://find.mtsu.edu/vufind/Search/Results?type=AllFields&filter%5B%5D=collection%3A%22Music+Collection%22"><?=$this->transEsc('Music Collection')?></a></li>
    </ul>
  </div>
</div>
