


<style>
body {background-image:url(http://walker.mtsu.edu/images/bg_header.png);
	background-repeat:repeat-x;}
    
   </style>



<? $account = $this->auth()->getManager(); ?>  
<div class="navbar-header">

<img class="hidden-xs" src="/vufind/themes/mtsu/images/vufind_logo.png" id="n00000001" usemap="#m_00000001" alt="" /><map name="m_00000001" id="m_00000001">
<area shape="rect" coords="720,27,932,64" href="https://library.mtsu.edu/borrow/accounts" alt="My Library Accounts" /><area shape="rect" coords="27,0,186,114" href="http://library.mtsu.edu" title="Library home" alt="Library Home" />
<area shape="rect" coords="227,72,660,122" href="https://find.mtsu.edu" alt="MTSU Libraries Catalog" />
<area shape="poly" coords="586,0,660,0,660,28,586,28,586,0" href="http://www.mtsu.edu/contact.php" alt="MTSU Directory" />
<area shape="poly" coords="462,0,577,0,577,28,462,28,462,0" href="http://www.goblueraiders.com/" alt="" />
<area shape="poly" coords="382,0,455,0,455,28,382,28,382,0" href="http://www.mtsu.edu/email/index.php" alt="MTSU Email" />
<area shape="poly" coords="297,0,376,0,376,28,297,28,297,0" href="http://pipeline.mtsu.edu/" alt="Pipeline" />
<area shape="poly" coords="216,0,294,0,294,28,216,28,216,0" href="http://www.mtsu.edu/atoz.php" alt="MTSU A-Z" />
<area shape="poly" coords="727,72,960,72,960,127,725,122,727,72" href="https://library.mtsu.edu/about/hours" title="Today's Hours" alt="Today's Hours" />
</map><a href="http://library.mtsu.edu"><img class="hidden-sm hidden-lg hidden-md" src="/vufind/themes/mtsu/images/vufind_logo_sm.png"></a>

  <!--<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse">
    <span class="sr-only">Toggle navigation</span>
    <i class="fa fa-bars"></i>
  </button>
  <a role="logo" class="navbar-brand" href="http://library.mtsu.edu"></a><br /><br />
 <!-- <p><strong><a href="<?=$this->url('home')?>">Start a New Search </a></strong></p>-->
</div>
<? if ($this->layout()->searchbox !== false): ?>
  <section class="visible-lg">
    <?=$this->layout()->searchbox ?>
  </section>
<? endif; ?>
<? if (!isset($this->layout()->renderingError)): ?>
  <div class="collapse navbar-collapse" id="header-collapse">
    <ul role="navigation" class="nav navbar-nav navbar-right">
     <li><a href="<?=$this->url('home')?>">Start a New Search</a></li>
     <li><a href="/vufind/Search/Advanced" rel="nofollow">Advanced Search</a></li>
     <li><a href="http://libanswers.mtsu.edu/">Ask a Librarian</a></li>
        <li><a href="/vufind/Browse/Home">Browse</a></li>
        <li><a href="/vufind/Search/Reserves">Course Reserves</a></li>
        <li><a href="/vufind/Search/History">Search History</a></li>
        <li><a href="http://library.mtsu.edu/ill">Borrow from Other Libraries</a></li> <? if ($this->feedback()->tabEnabled()): ?>
        <li>
          <a id="feedbackLink" class="modal-link" href="<?=$this->url('feedback-home') ?>"><i class="fa fa-envelope"></i> <?=$this->transEsc("Feedback")?></a>
        </li>
      <? endif; ?>
      <? $cart = $this->cart(); if ($cart->isActive()): ?>
        <li id="cartSummary">
          <a id="cartItems" class="modal-link" title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>"><i class="fa fa-suitcase"></i> <strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?><?=$cart->isFull() ? ' (' .  $this->transEsc('bookbag_full') . ')' : ''?></a>
        </li>
      <? endif; ?>
      <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
        <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
          <a href="<?=$this->url('myresearch-home', array(), array('query' => array('redirect' => 0)))?>" class="modal-link" title="<?=$this->transEsc("Your Account")?>"><i class="fa fa-home"></i> <?=$this->transEsc("Your Account")?></a>
        </li>
        <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
          <a href="<?=$this->url('myresearch-logout')?>" class="modal-link" title="<?=$this->transEsc("Log Out")?>"><i class="fa fa-sign-out"></i> <?=$this->transEsc("Log Out")?></a>
        </li>
        <li id="loginOptions"<? if($account->isLoggedIn()): ?> class="hidden"<? endif ?>>
          <? if ($sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
            <a href="<?=$this->escapeHtmlAttr($sessionInitiator)?>"><i class="fa fa-sign-in"></i> <?=$this->transEsc("Institutional Login")?></a>
          <? else: ?>
            <a href="https://library2.mtsu.edu/iii/cas/login?service=https%3A%2F%2Flibrary2.mtsu.edu%3A443%2Fpatroninfo~S1%2FIIITICKET&scope=1" class="modal-link" title="<?=$this->transEsc("Login")?>"><i class="fa fa-sign-in"></i> <?=$this->transEsc("Login")?></a>
          <? endif; ?>
        </li>
      <? endif; ?>

      <? if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
        <li class="dropdown">
          <form method="post" name="themeForm" action="" id="themeForm">
            <input type="hidden" name="ui"/>
          </form>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <? foreach ($this->layout()->themeOptions as $current): ?>
              <li<?=$current['selected'] ? ' class="active"' : ''?>><a href="#" onClick="document.themeForm.ui.value='<?=$this->escapeHtmlAttr($current['name'])?>';document.themeForm.submit()"><?=$this->transEsc($current['desc'])?></a></li>
            <? endforeach; ?>
          </ul>
        </li>
      <? endif; ?>

      <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
        <li class="dropdown">
          <form method="post" name="langForm" action="" id="langForm">
            <input type="hidden" name="mylang"/>
          </form>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Language")?> <b class="caret"></b></a>
          <ul class="dropdown-menu">
          <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
            <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>><a href="#" onClick="document.langForm.mylang.value='<?=$langCode?>';document.langForm.submit()"><?=$this->displayLanguageOption($langName)?></a></li>
          <? endforeach; ?>
          </ul>
        </li>
      <? endif; ?>
    </ul>
  </div>
<? endif; ?>
