<div class="form-group">
  <div class="input-group">
    <label class="col-sm-2 control-label for_login" for="login_username"><?=$this->transEsc('Username')?>:</label>    
    <input type="text" name="username" id="login_username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control"/>
    <span class="input-group-addon">@</span>
    <select id="select_inst" name="institution" class="form-control">
      <option selected="selected" value="">Choose One</option>
      <option value="brynmawr">Bryn Mawr</option>
      <option value="haverford">Haverford</option>
      <option value="swarthmore">Swarthmore</option>
    </select>
    <span class="input-group-addon login_edu">.edu</span>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-2 control-label for_login" for="login_password"><?=$this->transEsc('Password')?>:</label>
  <input type="password" name="password" id="login_password" class="form-control"/>
</div>
